version: '3.9'

services:
  app-ui:
    image: app-ui
    container_name: app-ui
    build:
      context: ./appui
      dockerfile: dev.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./appui:/app
      - /app/node_modules
    networks:
      - one-home-app-network

  api-server:
    image: api-server
    container_name: api-server
    command: [ "supervisor", "-e", "js,ts,html", "src/app.js" ]
    build:
      context: ./serverapi
      dockerfile: dev.Dockerfile
    volumes:
      - ./serverapi/src:/app/src
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - one-home-app-network
    environment:
      - SAMPLE_ENV_VAR=I Am From Docker Compose

networks:
  one-home-app-network:
    driver: bridge